name: ws_hwr_env
channels:
- defaults
- anaconda
- conda-forge
- byu-handwriting-lab
dependencies:
- python=3.7.3
- pip=20.3.3
- anaconda::numpy==1.19.1
- anaconda::redis==5.0.3
- anaconda::redis-py=3.5.3
- anaconda::flask=1.1.2
- anaconda::pillow=7.1.2
- conda-forge::matplotlib=3.3.3
- byu-handwriting-lab::hwr=0.1
- pip:
    - tensorflow==2.3.0